// <autogenerated/>

using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Polyclinic.Infrastructure.EfCore.Migrations;

/// <inheritdoc />
public partial class InitialCreate : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Doctors",
            columns: table => new
            {
                Id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                PassportNumber = table.Column<string>(type: "text", nullable: false),
                FullName = table.Column<string>(type: "text", nullable: false),
                BirthYear = table.Column<int>(type: "integer", nullable: false),
                Specialization = table.Column<int>(type: "integer", nullable: false),
                Experience = table.Column<int>(type: "integer", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Doctors", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "Patients",
            columns: table => new
            {
                Id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                PassportNumber = table.Column<string>(type: "text", nullable: false),
                FullName = table.Column<string>(type: "text", nullable: false),
                Gender = table.Column<int>(type: "integer", nullable: false),
                BirthDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                Address = table.Column<string>(type: "text", nullable: false),
                BloodGroup = table.Column<int>(type: "integer", nullable: false),
                RhesusFactor = table.Column<int>(type: "integer", nullable: false),
                Phone = table.Column<string>(type: "text", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Patients", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "Appointments",
            columns: table => new
            {
                Id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                PatientId = table.Column<int>(type: "integer", nullable: false),
                DoctorId = table.Column<int>(type: "integer", nullable: false),
                DateTime = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                RoomNumber = table.Column<int>(type: "integer", nullable: false),
                IsRepeat = table.Column<bool>(type: "boolean", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Appointments", x => x.Id);
                table.ForeignKey(
                    name: "FK_Appointments_Doctors_DoctorId",
                    column: x => x.DoctorId,
                    principalTable: "Doctors",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "FK_Appointments_Patients_PatientId",
                    column: x => x.PatientId,
                    principalTable: "Patients",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.InsertData(
            table: "Doctors",
            columns: new[] { "Id", "BirthYear", "Experience", "FullName", "PassportNumber", "Specialization" },
            values: new object[,]
            {
                { 1, 1970, 25, "Доктор Хаус", "D001", 0 },
                { 2, 1980, 15, "Айболит Иван", "D002", 4 },
                { 3, 1990, 8, "Сергеев Павел", "D003", 2 },
                { 4, 1985, 12, "Михайлова Ольга", "D004", 5 },
                { 5, 1975, 20, "Сидоров Алексей", "D005", 1 },
                { 6, 1992, 5, "Кузнецова Марина", "D006", 3 },
                { 7, 1983, 14, "Громов Олег", "D007", 8 },
                { 8, 1987, 11, "Иванова Татьяна", "D008", 7 },
                { 9, 1991, 9, "Павлова Светлана", "D009", 6 },
                { 10, 1984, 16, "Белый Роман", "D010", 9 }
            });

        migrationBuilder.InsertData(
            table: "Patients",
            columns: new[] { "Id", "Address", "BirthDate", "BloodGroup", "FullName", "Gender", "PassportNumber", "Phone", "RhesusFactor" },
            values: new object[,]
            {
                { 1, "ул. Ленина, 1", new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc), 0, "Иванов Иван", 0, "P001", "111-111", 0 },
                { 2, "ул. Гагарина, 2", new DateTime(1985, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc), 1, "Петров Петр", 0, "P002", "222-222", 1 },
                { 3, "ул. Молодежная, 5", new DateTime(1995, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc), 2, "Сидорова Анна", 1, "P003", "333-333", 0 },
                { 4, "ул. Советская, 9", new DateTime(2000, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc), 0, "Кузнецов Сергей", 0, "P004", "444-444", 1 },
                { 5, "ул. Победы, 10", new DateTime(1978, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc), 3, "Смирнова Мария", 1, "P005", "555-555", 0 },
                { 6, "ул. Центральная, 12", new DateTime(1992, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc), 1, "Орлов Дмитрий", 0, "P006", "666-666", 0 },
                { 7, "ул. Чехова, 3", new DateTime(1988, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc), 2, "Васильева Ирина", 1, "P007", "777-777", 1 },
                { 8, "ул. Спортивная, 4", new DateTime(1999, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc), 0, "Морозов Алексей", 0, "P008", "888-888", 0 },
                { 9, "ул. Пушкина, 8", new DateTime(1980, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc), 3, "Николаева Елена", 1, "P009", "999-999", 1 },
                { 10, "ул. Луговая, 6", new DateTime(1993, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc), 1, "Зайцев Павел", 0, "P010", "101-010", 0 }
            });

        migrationBuilder.InsertData(
            table: "Appointments",
            columns: new[] { "Id", "DateTime", "DoctorId", "IsRepeat", "PatientId", "RoomNumber" },
            values: new object[,]
            {
                { 1, new DateTime(2025, 8, 15, 14, 50, 0, 0, DateTimeKind.Utc), 1, false, 1, 101 },
                { 2, new DateTime(2025, 6, 30, 12, 30, 0, 0, DateTimeKind.Utc), 2, true, 2, 102 },
                { 3, new DateTime(2025, 10, 30, 12, 0, 0, 0, DateTimeKind.Utc), 3, false, 3, 103 },
                { 4, new DateTime(2025, 6, 7, 11, 30, 0, 0, DateTimeKind.Utc), 4, true, 4, 104 },
                { 5, new DateTime(2025, 6, 10, 12, 20, 0, 0, DateTimeKind.Utc), 5, true, 5, 105 },
                { 6, new DateTime(2025, 7, 24, 10, 0, 0, 0, DateTimeKind.Utc), 5, false, 6, 105 },
                { 7, new DateTime(2025, 6, 1, 12, 30, 0, 0, DateTimeKind.Utc), 1, true, 6, 101 },
                { 8, new DateTime(2025, 3, 30, 14, 30, 0, 0, DateTimeKind.Utc), 3, false, 7, 103 },
                { 9, new DateTime(2025, 6, 17, 12, 0, 0, 0, DateTimeKind.Utc), 8, true, 8, 108 },
                { 10, new DateTime(2025, 8, 8, 16, 30, 0, 0, DateTimeKind.Utc), 9, false, 9, 108 },
                { 11, new DateTime(2025, 9, 27, 12, 24, 0, 0, DateTimeKind.Utc), 10, true, 10, 109 }
            });

        migrationBuilder.CreateIndex(
            name: "IX_Appointments_DoctorId",
            table: "Appointments",
            column: "DoctorId");

        migrationBuilder.CreateIndex(
            name: "IX_Appointments_PatientId",
            table: "Appointments",
            column: "PatientId");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Appointments");

        migrationBuilder.DropTable(
            name: "Doctors");

        migrationBuilder.DropTable(
            name: "Patients");
    }
}
