// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Polyclinic.Infrastructure.EfCore;

#nullable disable

namespace Polyclinic.Infrastructure.EfCore.Migrations;

[DbContext(typeof(PolyclinicDbContext))]
partial class PolyclinicDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Polyclinic.Domain.Appointment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DateTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("DoctorId")
                    .HasColumnType("integer");

                b.Property<bool>("IsRepeat")
                    .HasColumnType("boolean");

                b.Property<int>("PatientId")
                    .HasColumnType("integer");

                b.Property<int>("RoomNumber")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.ToTable("Appointments");

                b.HasData(
                    new
                    {
                        Id = 1,
                        DateTime = new DateTime(2025, 8, 15, 14, 50, 0, 0, DateTimeKind.Utc),
                        DoctorId = 1,
                        IsRepeat = false,
                        PatientId = 1,
                        RoomNumber = 101
                    },
                    new
                    {
                        Id = 2,
                        DateTime = new DateTime(2025, 6, 30, 12, 30, 0, 0, DateTimeKind.Utc),
                        DoctorId = 2,
                        IsRepeat = true,
                        PatientId = 2,
                        RoomNumber = 102
                    },
                    new
                    {
                        Id = 3,
                        DateTime = new DateTime(2025, 10, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                        DoctorId = 3,
                        IsRepeat = false,
                        PatientId = 3,
                        RoomNumber = 103
                    },
                    new
                    {
                        Id = 4,
                        DateTime = new DateTime(2025, 6, 7, 11, 30, 0, 0, DateTimeKind.Utc),
                        DoctorId = 4,
                        IsRepeat = true,
                        PatientId = 4,
                        RoomNumber = 104
                    },
                    new
                    {
                        Id = 5,
                        DateTime = new DateTime(2025, 6, 10, 12, 20, 0, 0, DateTimeKind.Utc),
                        DoctorId = 5,
                        IsRepeat = true,
                        PatientId = 5,
                        RoomNumber = 105
                    },
                    new
                    {
                        Id = 6,
                        DateTime = new DateTime(2025, 7, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                        DoctorId = 5,
                        IsRepeat = false,
                        PatientId = 6,
                        RoomNumber = 105
                    },
                    new
                    {
                        Id = 7,
                        DateTime = new DateTime(2025, 6, 1, 12, 30, 0, 0, DateTimeKind.Utc),
                        DoctorId = 1,
                        IsRepeat = true,
                        PatientId = 6,
                        RoomNumber = 101
                    },
                    new
                    {
                        Id = 8,
                        DateTime = new DateTime(2025, 3, 30, 14, 30, 0, 0, DateTimeKind.Utc),
                        DoctorId = 3,
                        IsRepeat = false,
                        PatientId = 7,
                        RoomNumber = 103
                    },
                    new
                    {
                        Id = 9,
                        DateTime = new DateTime(2025, 6, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                        DoctorId = 8,
                        IsRepeat = true,
                        PatientId = 8,
                        RoomNumber = 108
                    },
                    new
                    {
                        Id = 10,
                        DateTime = new DateTime(2025, 8, 8, 16, 30, 0, 0, DateTimeKind.Utc),
                        DoctorId = 9,
                        IsRepeat = false,
                        PatientId = 9,
                        RoomNumber = 108
                    },
                    new
                    {
                        Id = 11,
                        DateTime = new DateTime(2025, 9, 27, 12, 24, 0, 0, DateTimeKind.Utc),
                        DoctorId = 10,
                        IsRepeat = true,
                        PatientId = 10,
                        RoomNumber = 109
                    });
            });

        modelBuilder.Entity("Polyclinic.Domain.Doctor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("BirthYear")
                    .HasColumnType("integer");

                b.Property<int>("Experience")
                    .HasColumnType("integer");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PassportNumber")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Specialization")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Doctors");

                b.HasData(
                    new
                    {
                        Id = 1,
                        BirthYear = 1970,
                        Experience = 25,
                        FullName = "Доктор Хаус",
                        PassportNumber = "D001",
                        Specialization = 0
                    },
                    new
                    {
                        Id = 2,
                        BirthYear = 1980,
                        Experience = 15,
                        FullName = "Айболит Иван",
                        PassportNumber = "D002",
                        Specialization = 4
                    },
                    new
                    {
                        Id = 3,
                        BirthYear = 1990,
                        Experience = 8,
                        FullName = "Сергеев Павел",
                        PassportNumber = "D003",
                        Specialization = 2
                    },
                    new
                    {
                        Id = 4,
                        BirthYear = 1985,
                        Experience = 12,
                        FullName = "Михайлова Ольга",
                        PassportNumber = "D004",
                        Specialization = 5
                    },
                    new
                    {
                        Id = 5,
                        BirthYear = 1975,
                        Experience = 20,
                        FullName = "Сидоров Алексей",
                        PassportNumber = "D005",
                        Specialization = 1
                    },
                    new
                    {
                        Id = 6,
                        BirthYear = 1992,
                        Experience = 5,
                        FullName = "Кузнецова Марина",
                        PassportNumber = "D006",
                        Specialization = 3
                    },
                    new
                    {
                        Id = 7,
                        BirthYear = 1983,
                        Experience = 14,
                        FullName = "Громов Олег",
                        PassportNumber = "D007",
                        Specialization = 8
                    },
                    new
                    {
                        Id = 8,
                        BirthYear = 1987,
                        Experience = 11,
                        FullName = "Иванова Татьяна",
                        PassportNumber = "D008",
                        Specialization = 7
                    },
                    new
                    {
                        Id = 9,
                        BirthYear = 1991,
                        Experience = 9,
                        FullName = "Павлова Светлана",
                        PassportNumber = "D009",
                        Specialization = 6
                    },
                    new
                    {
                        Id = 10,
                        BirthYear = 1984,
                        Experience = 16,
                        FullName = "Белый Роман",
                        PassportNumber = "D010",
                        Specialization = 9
                    });
            });

        modelBuilder.Entity("Polyclinic.Domain.Patient", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("BloodGroup")
                    .HasColumnType("integer");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Gender")
                    .HasColumnType("integer");

                b.Property<string>("PassportNumber")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("RhesusFactor")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Patients");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Address = "ул. Ленина, 1",
                        BirthDate = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 0,
                        FullName = "Иванов Иван",
                        Gender = 0,
                        PassportNumber = "P001",
                        Phone = "111-111",
                        RhesusFactor = 0
                    },
                    new
                    {
                        Id = 2,
                        Address = "ул. Гагарина, 2",
                        BirthDate = new DateTime(1985, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 1,
                        FullName = "Петров Петр",
                        Gender = 0,
                        PassportNumber = "P002",
                        Phone = "222-222",
                        RhesusFactor = 1
                    },
                    new
                    {
                        Id = 3,
                        Address = "ул. Молодежная, 5",
                        BirthDate = new DateTime(1995, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 2,
                        FullName = "Сидорова Анна",
                        Gender = 1,
                        PassportNumber = "P003",
                        Phone = "333-333",
                        RhesusFactor = 0
                    },
                    new
                    {
                        Id = 4,
                        Address = "ул. Советская, 9",
                        BirthDate = new DateTime(2000, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 0,
                        FullName = "Кузнецов Сергей",
                        Gender = 0,
                        PassportNumber = "P004",
                        Phone = "444-444",
                        RhesusFactor = 1
                    },
                    new
                    {
                        Id = 5,
                        Address = "ул. Победы, 10",
                        BirthDate = new DateTime(1978, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 3,
                        FullName = "Смирнова Мария",
                        Gender = 1,
                        PassportNumber = "P005",
                        Phone = "555-555",
                        RhesusFactor = 0
                    },
                    new
                    {
                        Id = 6,
                        Address = "ул. Центральная, 12",
                        BirthDate = new DateTime(1992, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 1,
                        FullName = "Орлов Дмитрий",
                        Gender = 0,
                        PassportNumber = "P006",
                        Phone = "666-666",
                        RhesusFactor = 0
                    },
                    new
                    {
                        Id = 7,
                        Address = "ул. Чехова, 3",
                        BirthDate = new DateTime(1988, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 2,
                        FullName = "Васильева Ирина",
                        Gender = 1,
                        PassportNumber = "P007",
                        Phone = "777-777",
                        RhesusFactor = 1
                    },
                    new
                    {
                        Id = 8,
                        Address = "ул. Спортивная, 4",
                        BirthDate = new DateTime(1999, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 0,
                        FullName = "Морозов Алексей",
                        Gender = 0,
                        PassportNumber = "P008",
                        Phone = "888-888",
                        RhesusFactor = 0
                    },
                    new
                    {
                        Id = 9,
                        Address = "ул. Пушкина, 8",
                        BirthDate = new DateTime(1980, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 3,
                        FullName = "Николаева Елена",
                        Gender = 1,
                        PassportNumber = "P009",
                        Phone = "999-999",
                        RhesusFactor = 1
                    },
                    new
                    {
                        Id = 10,
                        Address = "ул. Луговая, 6",
                        BirthDate = new DateTime(1993, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                        BloodGroup = 1,
                        FullName = "Зайцев Павел",
                        Gender = 0,
                        PassportNumber = "P010",
                        Phone = "101-010",
                        RhesusFactor = 0
                    });
            });

        modelBuilder.Entity("Polyclinic.Domain.Appointment", b =>
            {
                b.HasOne("Polyclinic.Domain.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Polyclinic.Domain.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Doctor");

                b.Navigation("Patient");
            });
#pragma warning restore 612, 618
    }
}
